--- 
jobs: 
  build: 
    machine: 
      image: "circleci/classic:latest"
    steps: 
      - checkout
      - 
        run: 
          command: |
              git config user.email "test@example.com"
              git config user.name "CircleCI"
          name: "Build Setup"
      - 
        run: 
          command: "./build.sh -n\n"
          name: "Kernel Build"
      - 
        run: 
          command: |
              - if [ "$CIRCLE_BRANCH" = "release" ]; then
              - curl https://github.com/tcnksm/ghr/releases/download/v0.12.2/ghr_v0.12.2_linux_amd64.tar.gz ;
              - tar -xvf ghr_v0.12.2_linux_amd64.tar.gz ;
              - chmod +x ghr_v0.12.2_linux_amd64/ghr ;
              - echo $(version_increment $(cat .circleci/version)) > .circleci/version ;
              - ghr_v0.12.2_linux_amd64/ghr -t ${JARED_API_KEY} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${.circleci/version} ./boot-image/out/ ;
              - fi
          name: "Check Branch"
      - 
        run: 
          command: |
              git gc
              make clobber
          name: "Clean up"
      - 
        save_cache: 
          key: "ccache-cache-cache-v1-{{ .Branch }}-{{ .Revision }}"
          paths: 
            - ~/.ccache
      - 
        save_cache: 
          key: "repo-v1-{{ .Branch }}-{{ .Revision }}"
          paths: 
            - ./
version: 2

