version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
      
    steps:
      # Checkout new change(s) not in cache
      - checkout
      # Set git identifiers and set up repo and swap
      - run:
          name: Build Setup
          command: |
            git config user.email "test@example.com"
            git config user.name "CircleCI"
      # Run build script
      - run:
          name: Kernel Build
          command: |
            ./build.sh -n
            
      # ADD DEPLOY STUFF HERE
      # ADD DEPLOY STUFF HERE
      # ADD DEPLOY STUFF HERE
      # ADD DEPLOY STUFF HERE
